# This is a basic workflow to help you get started with Actions
name: GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: yunwei37/OpenAI-Continuous-Translator@master
        with:
            git_repo_url: https://github.com/warklock2912/diablo2-tyrael-might-vn
            api_key: ${{ secrets.OPENAI_API_KEY }}
            source_language: vi_VN
            target_language: en_EN
            additional_prompt: "What is Diablo 2 Game ?"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
